<?php

/**
 * @file
 * Contains custom_modal.module.
 */

use Drupal\Component\Serialization\Json;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\service_club_event\Entity\EventInformation;


/**
 * Implements hook_help().
 */
function custom_modal_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_modal module.
    case 'help.page.custom_modal':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Display a Modal') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function custom_modal_theme() {
  return [
    'custom_modal' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * @param array $build
 * @param \Drupal\service_club_event\Entity\EventInformation $entity
 * @param \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display
 * @param $view_mode
 */
function custom_modal_event_information_view(
  array &$build,
  EventInformation $entity,
  EntityViewDisplayInterface $display,
  $view_mode
) {
  $userID = $entity->getOwner()->id(); // the auther of the event
  $eventID = $entity->id();      // the ID of the event
  dd($userID);
  dd($eventID);

  $link_url = Url::fromRoute('custom_modal.modal', array('entityid' => 'hello'));
  //$link_url->setRouteParameter('entityid',$eventID);
  $link_url->setOptions([
    'attributes' => [
      'class' => ['use-ajax', 'button', 'button--small'],
      'data-dialog-type' => 'modal',
      'data-dialog-options' => Json::encode(['width' => 800]),
    ],
  ]);

  $build['modal_button'] = [
    '#type' => 'markup',
    '#markup' => Link::fromTextAndUrl(t('Open modal'), $link_url)
      ->toString(),
    '#attached' => [
      'library' => [
        'core/drupal.dialog.ajax',
      ],
    ],
  ];

  // Load the jwtAuth service and generate a token.
  // Make sure your website has a key set in the JWT admin page.
  $jwtAuth = \Drupal::service('jwt.authentication.jwt');
  $jwtKey = $jwtAuth->generateToken();

  // $jwtKey = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MzY3MjQxNjcsImV4cCI6MTUzNjcyNzc2NywiZHJ1cGFsIjp7InVpZCI6IjIifX0.s-_tdfCTmv24ti8ruZ9rPkGiBHzQZTJCf3K-qorVifg';
//  $jwtKey = \Drupal\jwt\Authentication\JwtGeneratorInterface::generateToken();
  $build['#attached']['drupalSettings']['app_data']['jwtkey'] = $jwtKey;
  $build['#attached']['drupalSettings']['app_data']['eventid'] = $eventID;
}

